# Setup
title:               'Karthik blog'
tagline:             ''
description:         ''
url:                 https://k-metric.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Karthik
  url:               https://twitter.com/k-metric

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
